//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG6212_Task2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Completed_Hours
    {
        public int CompHours_ID { get; set; }
        public System.DateTime date { get; set; }
        public int hours { get; set; }
        public Nullable<int> ID { get; set; }
    
        public virtual Module Module { get; set; }
    }
}
