//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PROG6212_Task2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Module
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Module()
        {
            this.Completed_Hours = new HashSet<Completed_Hours>();
        }
    
        public int ID { get; set; }
        public string Module_Code { get; set; }
        public string Module_Name { get; set; }
        public int Credits { get; set; }
        public int Weekly_Hours { get; set; }
        public int Semester_Weeks { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Completed_Hours> Completed_Hours { get; set; }
        public virtual User User { get; set; }
    }
}
